### ISSUE TITLE
Missing file `data/ares.pt`

### ISSUE THREAD

**Issue by erip** [SapienzaNLP/reducing-wsd-bias-in-nmt#5]
When fine-tuning a model, the training crashes because of [this line](https://github.com/SapienzaNLP/reducing-wsd-bias-in-nmt/blob/614f0e33ce18077bfd3bb04524565fea6c582796/src/model/sense_embedding.py#L11) which requires the ARES embeddings to be loaded. I downloaded the ARES embeddings from [here](http://sensembert.org/) but I'm not sure how to format them to make them ingestible by this code. 

Is there a script you can share to appropriately format them? If so, I can update the README.

**Comment by Valahaar** [comment]
Wow, I'm impressed I actually forgot to link ARES, sorry! :scream: 

https://drive.google.com/file/d/1wSXUr7-k2n_YvSwbbfrlUtAf5HPbC89m/view

Thanks for pointing this out, I'll update the README with the link :)
